In [2]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *


import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv("diabeties.csv")
df

pregnant  glocose  bp  skin  insulin   bmi  predigree  age  target
0           6      148  72    35        0  33.6      0.627   50       1
1           1       85  66    29        0  26.6      0.351   31       0
2           8      183  64     0        0  23.3      0.672   32       1
3           1       89  66    23       94  28.1      0.167   21       0
4           0      137  40    35      168  43.1      2.288   33       1
..        ...      ...  ..   ...      ...   ...        ...  ...     ...
763        10      101  76    48      180  32.9      0.171   63       0
764         2      122  70    27        0  36.8      0.340   27       0
765         5      121  72    23      112  26.2      0.245   30       0
766         1      126  60     0        0  30.1      0.349   47       1
767         1       93  70    31        0  30.4      0.315   23       0

[768 rows x 9 columns]

In [4]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [5]:
x


pregnant  glocose  bp  skin  insulin   bmi  predigree  age
0           6      148  72    35        0  33.6      0.627   50
1           1       85  66    29        0  26.6      0.351   31
2           8      183  64     0        0  23.3      0.672   32
3           1       89  66    23       94  28.1      0.167   21
4           0      137  40    35      168  43.1      2.288   33
..        ...      ...  ..   ...      ...   ...        ...  ...
763        10      101  76    48      180  32.9      0.171   63
764         2      122  70    27        0  36.8      0.340   27
765         5      121  72    23      112  26.2      0.245   30
766         1      126  60     0        0  30.1      0.349   47
767         1       93  70    31        0  30.4      0.315   23

[768 rows x 8 columns]

In [6]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: target, Length: 768, dtype: int64

In [7]:
xtrain ,xtest,ytrain, ytest = train_test_split(x,y,test_size=0.30,random_state=1)

In [17]:
lg = LogisticRegression()
lg.fit(xtrain,ytrain)
ypred = lg.predict(xtest)
print(classification_report(ytest,ypred))
print(roc_auc_score(ytest,ypred))

              precision    recall  f1-score   support

           0       0.79      0.90      0.84       146
           1       0.78      0.58      0.66        85

    accuracy                           0.78       231
   macro avg       0.78      0.74      0.75       231
weighted avg       0.78      0.78      0.78       231

0.740290088638195


In [18]:
print(confusion_matrix(ytest,ypred))

[[132  14]
 [ 36  49]]


In [20]:
lg.predict_proba(xtest)

array([[0.58039353, 0.41960647],
       [0.69594675, 0.30405325],
       [0.85394551, 0.14605449],
       [0.94499737, 0.05500263],
       [0.7904803 , 0.2095197 ],
       [0.72197204, 0.27802796],
       [0.64281392, 0.35718608],
       [0.89586717, 0.10413283],
       [0.83496336, 0.16503664],
       [0.78879666, 0.21120334],
       [0.56949866, 0.43050134],
       [0.92485901, 0.07514099],
       [0.01884594, 0.98115406],
       [0.27328597, 0.72671403],
       [0.97528159, 0.02471841],
       [0.28338177, 0.71661823],
       [0.76400001, 0.23599999],
       [0.69651293, 0.30348707],
       [0.8701194 , 0.1298806 ],
       [0.8440298 , 0.1559702 ],
       [0.61771632, 0.38228368],
       [0.86680566, 0.13319434],
       [0.04823513, 0.95176487],
       [0.73908068, 0.26091932],
       [0.92726134, 0.07273866],
       [0.59294462, 0.40705538],
       [0.79790386, 0.20209614],
       [0.27468183, 0.72531817],
       [0.91827756, 0.08172244],
       [0.54150403, 0.45849597],
       [0.

In [21]:
ypredprob = lg.predict_proba(xtest)[:,1]

In [22]:
ypredprob

array([0.41960647, 0.30405325, 0.14605449, 0.05500263, 0.2095197 ,
       0.27802796, 0.35718608, 0.10413283, 0.16503664, 0.21120334,
       0.43050134, 0.07514099, 0.98115406, 0.72671403, 0.02471841,
       0.71661823, 0.23599999, 0.30348707, 0.1298806 , 0.1559702 ,
       0.38228368, 0.13319434, 0.95176487, 0.26091932, 0.07273866,
       0.40705538, 0.20209614, 0.72531817, 0.08172244, 0.45849597,
       0.40716885, 0.32551303, 0.05376305, 0.70136257, 0.12924138,
       0.66577991, 0.08926392, 0.18089727, 0.10293623, 0.62329878,
       0.21034599, 0.08630756, 0.03882824, 0.28132453, 0.07063914,
       0.02336275, 0.75628149, 0.81145354, 0.07646832, 0.1422935 ,
       0.00859847, 0.17865559, 0.83456134, 0.05093263, 0.74527241,
       0.10062006, 0.61653819, 0.2982841 , 0.56270583, 0.1707134 ,
       0.616262  , 0.0131836 , 0.71596361, 0.22046119, 0.3740711 ,
       0.11151299, 0.01522905, 0.35658558, 0.70100985, 0.60283165,
       0.88110423, 0.75329695, 0.58198676, 0.01784901, 0.68146

In [19]:
from sklearn.preprocessing import binarize

In [29]:
ypred = binarize([ypredprob],threshold=0.20)[0]

In [30]:
ypred

array([1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1.,
       1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0.,
       0., 0., 1., 1., 1.

In [31]:
print(f"Actual values : {ytest[:25].values}")
print(f"Predicted Values : {ypred[:25].astype(int)}")

Actual values : [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0]
Predicted Values : [1 1 0 0 1 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0 1 0 1 1 0]


In [33]:
print(classification_report(ytest,ypred))
print(roc_auc_score(ytest,ypred))

              precision    recall  f1-score   support

           0       0.92      0.55      0.69       146
           1       0.54      0.92      0.68        85

    accuracy                           0.68       231
   macro avg       0.73      0.73      0.68       231
weighted avg       0.78      0.68      0.68       231

0.7327961321514906
